blank_issues_enabled: true
contact_links:
  - name: Chrome Web Store
    url: https://chromewebstore.google.com/detail/lingomon/panaoaejgjhkibbdmghgbgkmmkmcnkbo
    about: Install or review Lingomon on Chrome Web Store
